### ISSUE TITLE
Docs 0.9.4

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#1974]
## Breaking changes

- [x] DataGrid `SearchValue` changed from string to object type
- [x] Use Color instead of Background parameter on Progress component
- [x] `Dialog` parameter is removed from `ModalContent`

## Optimizations

- #1941 IAsyncDisposable

### Highlights 🚀

- Rating Components
- Async Validations
- Tippy.js is now running the Tooltip component
- Border utilities
- Flex utilities
- Sizing utilities
- Vertical alignment utility
- NoGutters utility
- Background color on base component
- Shadow utility
- Spinkit Implementation
- Table sticky header
- RowColumns utility
- Addons size parameter
- DatePicker and TimePicker
- Create services for messages and notifications
- Resizable Table Columns
- DataGrid API
- Carousel slide animation
- Markdown component
- DataGrid UpdateEditingCell API
- DataGrid Virtualize

### All features

- [x] #2023 Flatpickr for Material provider
- [x] #1997 Blazorise Material - First day of week
- [x] #1996 Rating Components
- [x] #1270 Async Validations
- [x] Disable button when Command can't execute
- [x] #2098 Modal VisibleChanged event (PR)
- [x] #2057 Clicked not working as expected for Button of type Link.
- [x] #2091 Add ValidationsSummaryErrors to DataGrid
- [x] #1401 SelectList defaultvalue
- [x] #2115 RTE: don't force users to use external source files
- [x] #2161 DataGrid: Extensible/Improved Aggregation
- [x] #1529 Tabs Components
- [x] #1703 NumericEdit Decimal not dynamically handled
- [x] #2140 Add support for Border utilities
- [x] #1966 Multisearch in the same column
- [x] #1978 Datagrid: Filter method by column // Enhancing Filter
- [x] #1416 Add Decimals and DecimalsSeparator to NumericEdit in the _BaseDataGridCellEdit for DataGridNumericColumn
- [x] #647 Change a button's disabled properties
- [x] #2116 Readonly or Disabled attribute for SelectList component
- [x] #1313 Tooltip on focus
- [x] #993 NumericEdit: add option to allow only positive values
- [x] #2200 ProgressBar percentage
- [x] #1733 NumericEdit with steps button
- [x] #2009 Datagrid: Multiselect: Shift+click
- [x] #2043 Add Clicked event on toggle components
- [x] #942 Implement more Utility classes
- [x] #2243 Add Condition to Display utility
- [x] #2103 Css-Cache for the ThemeGenerator
- [x] #2230 NumericEdit set ShowSpinButtons option globally
- [x] #2232 Modal Title HeadingSize
- [x] #2251 Move Typography parameters to BaseComponent class
- [x] #1040 Shadow utility
- [x] #1420 DataGrid row vertical alignment
- [x] #2272 Add Disabled to SelectList
- [x] #2281 DropdownHeader component
- [x] #1202 Icon size
- [x] #777 Spinkit Implementation
- [x] #2360 Implement Row Columns utility
- [x] #1840 Add Selectable parameter to ListGroup
- [x] #2383 SelectList Placeholder
- [x] #2062 Consider adding a custom date picker library
- [x] #2381 DateEdit Format property
- [x] #1998 Date: support for more DateInputModes: MonthYear and Year
- [x] #2347 Step DateEdit
- [x] #2401 Add overflow utility
- [x] #2391 Add a BarDropdownDivider
- [x] #1622 Simplify usage of progress component
- [x] #2409 Add TextOverflow utility enum for BaseTypographyComponent
- [x] #2472 Change Size globally - Theming
- [x] #2476 Placeholder for FileEdit
- [x] #2368 SpinKit .sk-center utility class
- [x] #1946 Bootstrap > Modal Dialog > Support modal-dialog-scrollable
- [x] #2422 New DatePicker recommendations
- [x] #2505 Consider renaming DataGridColumn.Direction to "SortDirection"
- [x] #1278 DataGridReadDataEventArgs does not provide order of sort columns
- [x] #1987 Support for multiple DataGridCommandColumn's
- [x] #1915 Clearing filters with a separate button (outside the DataGrid)
- [x] #784 DataGrid: property to expose count of unfiltered/filtered records
- [x] #2509 Add new enums for Tooltip Placement
- [x] #2508 Consider adding an overload of SnackbarStack.PushAsync that accepts a MarkupString
- [x] #1634 Create services for messages and notifications
- [x] #2313 Create column resize on Table
- [x] #1994 DataGrid API
- [x] #1745 Carousel component - slide animation not working
- [x] #1611 ChartJS (LineChart)Dataset: the ability to add series (Datasets) that are initially not displayed (hidden)
- [x] #1842 Chart: RemoveDataSet API
- [x] #2316 NumericEdit cannot disable numeric stepping from keyboard up/down
- [x] #2562 Add support for .Net 6
- [x] #2415 Add Markdown editor component
- [x] #2287 missing dataset labels on PieChart
- [x] #1014 Missing color in charts
- [x] #2513 Chart Font Options
- [x] #1067 Question How to change chart axis color
- [x] #1428 Charts : onmouseout Event
- [x] #1485 Autocomplete: Able to type freely
- [x] #1890 Suggestion: Select2 like component
- [x] #2550 Add EmptyFilterTemplate to datagrid
- [x] #2586 DataGrid UpdateEditingCell API
- [x] #2612 DataGrid Sort API
- [x] #1381 Virtualize option for Datagrid with .NET 5
- [x] #2646 Add Table ScrollToRow method
- [x] #2654 DataGridDateColumn contains time (minimum to seconds)

## Fixes

- [x] #1920 Blazor server - issue in component cleanup
- [x] #2014 Italian translating errors
- [x] #2042 RichTextEdit two way binding
- [x] #2110 2 Tooltip add break line
- [x] #1685 Tooltip is getting burried
- [x] #1888 Tooltip on button near right-edge of screen not re-positioning to fall within the screen width
- [x] #1739 tooltip - detect page width
- [x] #1257 Linebreak in Tooltip
- [x] #1664 Tooltip destroys ColumnSize
- [x] #1165 Divider Thickness don't apply to DividerType.TextContent
- [x] #1602 Autocomplete with some data containing null
- [x] #1696 NumericEdit issues with Min=0
- [x] #1892 NumericEdit Min="0" allows negative values
- [x] #1286 Strange step behaviour in NumericEdit
- [x] #1510 z-index issue with autocomplete (and other items)
- [x] #1618 Able to set color in header
- [x] #2329 Unable to change chart ratio
- [x] #2345 The value of DataGrid aggregate column will not be automatically updated with filtering
- [x] #1253 Fields with the data type of time do not generate input boxes automatically in edit mode
- [x] #2459 DropDown in a DataGrid does not "open"
- [x] #1104 Data grid initial sort direction is not working
- [x] #1682 DataGrid switching between Inline Edit and Display loses applied Style's in Edit template
- [x] #1283 LayoutHeader moving
- [x] #2547 BarThickness and MaxBarThickness
- [x] #2577 Datagrid: TableFixedHeader | White Space between header rows
- [x] #2621 Ant Design : Table : FixHeader Broken
- [x] #2629 Tooltip text is not updated on @bind-Text
- [x] #2639 DatePicker - Validation does not change border color
- [x] #2632 Set numerical field buttons deeper in the field
- [x] #2648 Fix closing of Bar from the separate BarToggler

### [teo-tsirpanis](https://github.com/teo-tsirpanis)

- #1972 Optimize the IdGenerator class.
- #1982 Use a cached delegate in the IdGenerator class.

### [andreatosato](https://github.com/andreatosato)

- #2031 Italian translation
- #2017 Rating component

### [njannink](https://github.com/njannink)

- #2070 ICommand.CanExecute behavior disables button
- #2113 RTE - Improvements to content update events
- #2124 RTE - Improvements to dynamic reference loading

### [belucha](https://github.com/belucha)

- ##2162 DataGrid aggregation function

### [imelnikova](https://github.com/imelnikova)

- #2205 Minor adjustments to translation in French

### [David-Moreira](https://github.com/David-Moreira)

- #2151 Datagrid: MultiSelect | ShiftClick Feature
- #2293 Table sticky header
- #2214 Table Fixed Header Feature

### [SkiTles55](https://github.com/SkiTles55)

- #2238 Russian Localization

### [FStolte](https://github.com/FStolte)

- #2153 Cache for the ThemeGenerator
- #2340 Store type mappings for ComponentActivator in Dictionary

### [czf](https://github.com/czf)

- #2325 Allowing updates for aspect ratio in charts

### [Jimmys20](https://github.com/Jimmys20)

- #2364 Bulma GenerateAlertVariantStyles fix
- #2365 Added Color property to ListGroupItem
- #2414 GenerateInputStyles fix
- #2454 move BaseAfterRenderComponent to Blazorise namespace

### [sturlath](https://github.com/sturlath)

- #2367 Icelandic localization for DataGrid,Carousel and FileEdit

### [mehmetuken](https://github.com/mehmetuken)

- #2369 Adding Turkish localizations

### [scottk4016](https://github.com/scottk4016)

- #2392 Add support for hidden default select item in SelectList component

### [codertimu](https://github.com/codertimu)

- #2572 Set selected slide on carouselSlide initialization

### [SimonCropp](https://github.com/SimonCropp)

- #2582 fix some spelling
- #2583 Spelling
- #2570 remove some redundant usings
- #2589 Missing using on HTTP client
- #2591 Remove redundant interpolation
- #2592 Use some null-coalescing assignment operators
- #2593 Use catch when
- #2594 Remove an incorrect region
- #2595 Remove redundant Delimiter ToString
- #2596 Remove redundant field
- #2590 Remove HttpClient from demos
- #2597 Slising => Sliding
- #2581 Remove some redundant state machines
- #2598 remove some null refs
- #2599 redundant verbatim prefix
- #2601 Simplify csproj files
- #2602 cleanup Blazorise.E2ETests
- #2603 Use target typed new
- #2605 Missing dispose
- #2606 Remove redundant SuppressFinalize
- #2607 Use some null propagation
- #2608 Formated to formatted
- #2610 Allow default for cancellation tokens
- #2609 Remove duplicate dictionary lookups

### [StefH](https://github.com/StefH)

- #2641 Add YAxisID to LineChartDataset and Add Id and Position to Axis
- #2644 Add Ticks Callback functionality

### [naefp](https://github.com/naefp)

- #2653 show dataset label in tooltip title on pie/doughnut charts
