### ISSUE TITLE
Docs 0.9.5

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#2724]
## Highlights

- .NET 6 ready
- .NET 5 latest version
- JS Modules
- Bootstrap 5 Provider
- Autocomplete tags
- Async refactoring's
- ColorPicker component
- Theme improvements
- InputMask Component

## Breaking changes

- Dropped `NotificationType`, `Message`, and `Title` from `NotificationAlert`
- Removed `void ValidateAll` in favor of `Task ValidateAll` on `Validations` component
- Removed `Title` component
- On `Dropdown`, `Toggled` removed in favor of `VisibleChanged`

## Features

- [x] #1103 Bootstrap 5 Provider
- [x] #2923 Async refactoring's (PR)
- [x] #2866 Container breakpoints
- [ ] #2836 New set of basic element components
- [x] #2740 For DataGrid Virtualize can we change Style=height... to be max-height?
- [x] #2834 Add ThemeContrast for DataGrid
- [x] #2877 Add VerticalItemsColumnSize to Tabs
- [x] #2681 Add Display utility to the DataGridColumn
- [x] #2830 Notification service Location missing (**for Documentation see PR** #2906 )
- [ ] #2844 BarIcon is missing IconSize parameter
- [x] #2875 Rename Link component
- [ ] #2757 Add Select method to input components
- [ ] #2719 New documentation app
- [ ] #2835 New set of utilities
- [x] #2883 Datagrid edit and save with enter key
- [ ] #2905 TextRole add entry for "tel"
- [x] #2825 Disable range of dates in DatePicker
- [ ] #2551 Refactor closable components
- [x] #2810 Modal Closing is an Action instead of an EventCallback
- [x] #1359 Modal - Show event
- [x] #625 Datagrid: SortField Feature
- [x] #2984 Autocomplete tags
- [x] #2656 ColorPicker component
- [x] #2135 Enable input of tabs in Memo
- [x] #2898 Import JavaScript on-demand with IJSObjectReference
- [x] #3015 Fix chartjs-plugin-streaming CDN
- [x] #1108 ListView component
- [x] #3009 Remove Title component
- [x] #2733 DataGrid PopupClosing event
- [x] #1862 NumericEdit select all on focus
- [x] #2969 Autocomplete HTML in DropDown list
- [x] #2774 Add VisibleChanged callback to Dropdown
- [x] #1236 Be able to modify the type of chart dynamically
- [x] #2441 RTL naming support
- [x] #2714 Markdown editor downloads FontAwesome
- [x] #2713 Markdown extension custom toolbar
- [x] #2696 Scoped Services causes issues with Blazor in Maui
- [x] #2837 Theme improvements
- [x] #3029 Shared data optimizations
- [x] #2532 Datagrid : ToggleDetailRow : Public Api Feature
- [x] #2500 DetailRowTrigger on DataGrid is called twice on each row click
- [x] #3061 Additional Validators
- [x] #2885 Theme bar gradient background
- [x] #1358 HTML 5 datalist or equivalent
- [x] #2284 Lazy load of tab content
- [x] #3088 Update to latest .Net 5.0.x
- [x] #3079 DataGrid : Permit DataGridColumn usage without specifying Field Parameter
- [x] #1066 InputMask Component
- [x] #3096 Set MemoEdit height to show all text
- [x] #3092 DataGrid RowSelectable EventArgs
- [x] #439 Modal Width

## Fixes

- [ ] #2872 DataGrid command column has multiple width attributes
- [ ] #1559 Nested Dropdowns malfunctioning
- [ ] #2138 Escape key in Autocomplete component closes Modal
- [x] #2855 DataGridColumn with null field exception
- [x] #3013 Bootstrap 5 Datagrid MultiSelect -- Fix checkboxes not working
- [x] #2998 Make snackbar show/hide methods awaitable
- [x] #2564 Dropdown menu goes behind div content : Bulma
- [x] #3050 DataGrid example for Editing not showing cancel/save buttons
- [x] #2330 Incorrect default margin on sidebar/vertical bar BarMenu for desktop breakpoints
- [x] #3083 Issues with PopupClosing in DataGrid
- [x] #3069 utocomplete dropdown in modal dialog closes when scroll bar used

## Demo

- #2720 Split demo app example into more subpages

### [maisak](https://github.com/maisak)

- #2723 Added intervals configuration for NotificationAlert component

### [maisak](https://github.com/puschie286)

- #2829 DataGrid: edit item creator

### [StefH](https://github.com/StefH)

- #2707 chartjs: Add support for Formattable String Expression

**Comment by David-Moreira** [comment]
@stsrki 
This seems like a 0.9.4 issue? 
-DatagridEditMode.Popup don't close Dialog after Save #2722
Did you happen to add this here by mistake?

**Comment by stsrki** [comment]
Yeah it is wrong copy paste. Can you fix it? Im on mobile currently!
